sudo: required
services:
  - docker

before_install:
  - docker build -t sandeepblh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sandeepblh/react-test npm test -- --coverage

after_success:
  - docker build -t sandeepblh/multi-client ./client
  - docker build -t sandeepblh/multi-nginx ./nginx
  - docker build -t sandeepblh/multi-server ./server
  - docker build -t sandeepblh/multi-worker ./worker
  #Lg in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdio
  #Take those images and push to dockerhub
  - docker push sandeepblh/multi-client
  - docker push sandeepblh/multi-nginx
  - docker push sandeepblh/multi-server
  - docker push sandeepblh/multi-worker
